#  Assignment 5

This assignment covers material on matrices, norms, condition numbers and eigensystems.

The breakdown of the marks is as follows:

Question 0 - [1 mark]  
Question 1 - [7 marks]  
Questino 2 - [6 marks]  
Question 3 - [7 marks]  
Question 4 - [9 marks]  

# Question 0

You should have saved this notebook to your ACM20030-Assignments folder. Now:
- commit the notebook to your local repository
- push the changes to the GitHub

In [3]:
import numpy as np
from numpy import linalg as la
np.set_printoptions(linewidth=200)  # This stops line wrapping of larger matrices

# Question 1 - practice manipulating arrays

This questions asks you write a few functions for manipulating arrays of data

## Q1 a

Write a function that checks if a given $n\times n$ matrix is symmetric. Use only loops and `.shape` function from numpy (do not use any other special numpy functions).

In [4]:
def SymmetryCheck(A):
    (m, n) = A.shape
    if (m!=n):
        print("Matrix is not square")
        return
    i=0
    while i<(m-1):
        x, y=A[i:,i], A[i,i:]
        for j in range(1, len(x)):
            if x[j]!=y[j]:
                print("Matrix is not symmetric")
                return
               
        i+=1
    print("Matrix is symmetric")
    return

Test your function on the two matrices below

In [5]:
A = np.random.rand(5,5)
SymMatrix = (A + A.T)/2

In [6]:
#A
SymmetryCheck(A)
#SymMatrix
SymmetryCheck(SymMatrix)

Matrix is not symmetric
Matrix is symmetric


## Q1 b

Write a function to transpose a general $n\times n$ matrix. Do this by writing loops and not using any special functions like `np.transpose()`, `A.T`, or any functions from any other library (`np.zeroes`, `np.ones`, `np.shape`, etc are all ok to use).

In [7]:
def MatrixTranspose(A):
    (m, n) = A.shape
    if (m!=n):
        print("Matrix is not square")
        return
    i=0
    while i<(m-1):
        x, y=A[i:,i], A[i,i:]
        for j in range(1, len(x)):
            temp=y[j]
            y[j]=x[j]
            x[j]=temp
               
        i+=1
    return A

Check your code by transposing a matrix by checking that $A^T \neq A$ and $(A^T)^T - A = 0$

In [10]:
A = np.random.rand(6,6);
print("Matrix A\n",A)
print("Transpose of A\n", MatrixTranspose(A))
print("(A transpose)transpose - A\n", MatrixTranspose(MatrixTranspose(A))-A )

Matrix A
 [[0.36327056 0.02060262 0.56113095 0.10396628 0.54828743 0.21763523]
 [0.2841513  0.18952878 0.65258585 0.17760009 0.81536361 0.29798831]
 [0.64948641 0.63581716 0.52222509 0.78913241 0.53205611 0.62652152]
 [0.1793684  0.99327301 0.42656026 0.4201772  0.60764154 0.01525638]
 [0.31329866 0.42130983 0.19383268 0.88354929 0.40019846 0.13747917]
 [0.32121828 0.85175026 0.7425516  0.92060316 0.81199252 0.12250838]]
Transpose of A
 [[0.36327056 0.2841513  0.64948641 0.1793684  0.31329866 0.32121828]
 [0.02060262 0.18952878 0.63581716 0.99327301 0.42130983 0.85175026]
 [0.56113095 0.65258585 0.52222509 0.42656026 0.19383268 0.7425516 ]
 [0.10396628 0.17760009 0.78913241 0.4201772  0.88354929 0.92060316]
 [0.54828743 0.81536361 0.53205611 0.60764154 0.40019846 0.81199252]
 [0.21763523 0.29798831 0.62652152 0.01525638 0.13747917 0.12250838]]
(A transpose)transpose - A
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 

## Q1c

Write a function that finds the maximum entry in a matrix (where the matrix does not need to be square). Do this by writing loops and not using any special functions like `np.max` or any functions from any other library.

In [11]:
def MatrixMax(A):
    i=0
    m=A[0,0]
    while i<A.shape[0]:
        x=A[i,:]
        for j in range(0, len(x)):
            if x[j]>m:
                m=x[j]
        i+=1
    return m

Check your result by comparing to `np.max(A)` for the below random matrix

In [15]:
A = np.random.rand(4,5)

print(A,"\nMaximum entry in A:",MatrixMax(A))
print("From np.max(A):", np.max(A))

[[0.29764362 0.56282327 0.09734183 0.87326859 0.78907338]
 [0.67092081 0.22381049 0.33472664 0.2363807  0.00716529]
 [0.53905054 0.86380607 0.45156324 0.15278741 0.65371346]
 [0.90994064 0.80118709 0.00783161 0.16711729 0.26790016]] 
Maximum entry in A: 0.9099406390385743
From np.max(A): 0.9099406390385743


Commit your notebook to git and push it to GitHub.

# Question 2:  matrix norms

In the lectures we focused on the $L^2$-norm. We also briefly mentioned the $L^1$ and $L^\infty$ norm. Let's look at calculating those as well for a general $m\times n$ matrix.

# Q2a

The $L^1$ norm is given by

$$ \lVert A \rVert_1 = \max_j \sum^m_{i=1} |a_{ij}| $$

i.e., it is the max of the sums of the absolute values of each column. Write a function that computes the $L^1$-norm using only loops. The function should use no special numpy functions except `np.abs()` (`np.shape`, `np.inf`, etc are ok to use).

In [16]:
def L1Norm(A):
    i=0
    n=0
    while i<A.shape[1]:
        m=0
        x=A[:,i]
        for j in range(0, len(x)):
            m+=x[j]
        if np.abs(m)>n:
            n=np.abs(m)
        i+=1
    return n

Check your result against NumPy's `la.norm(A,1)` function for the following random matrix

In [20]:
A = np.random.rand(3,4)
print(A)
print("Using L1Norm function, L1 norm =",L1Norm(A))
print("Using la.norm(A,1), L1 norm =",la.norm(A,1))


[[0.28980424 0.62147454 0.76663447 0.10587598]
 [0.52308515 0.40117613 0.99883655 0.61516134]
 [0.26639376 0.22282019 0.2788635  0.2573484 ]]
Using L1Norm function, L1 norm = 2.044334514699379
Using la.norm(A,1), L1 norm = 2.044334514699379


## Q2b

The $L^\infty$ norm is given by 

$$\lVert A \rVert_\infty = \max_i \sum_{j=1}^n |a_{ij}|$$

i.e., it is the max of the sums of the absolute values of each row. Write a function that computes the $L^\infty$-norm using only loops and no special numpy functions.

In [21]:
def LinfNorm(A):
    i=0
    n=0
    while i<A.shape[0]:
        m=0
        x=A[i,:]
        for j in range(0, len(x)):
            m+=x[j]
        if np.abs(m)>n:
            n=np.abs(m)
        i+=1
    return n

Check your result against NumPy's `la.norm(A,np.inf)` function for the following random matrix

In [22]:
A = np.random.rand(3,4)
print(A)
print("Using LinfNorm function, L infinity norm =",LinfNorm(A))
print("Using la.norm(A,np.inf), L infinity norm =",la.norm(A,np.inf))

[[0.58761567 0.59931307 0.02361257 0.25363065]
 [0.07670831 0.42451674 0.16821347 0.23651875]
 [0.90321026 0.49054779 0.8681444  0.33281239]]
Using LinfNorm function, L infinity norm = 2.594714843168473
Using la.norm(A,np.inf), L infinity norm = 2.594714843168473


Commit your notebook to git and push it to GitHub.

# Question 3: ill-conditions systems of equations

In this question you can use any of NumPy's functions.

## Q3a

Which of the following three matrices, $A1, A2, A3$, are ill-conditioned. State the reason for your conclusion.

In [23]:
A1 = np.array([[ 2.852416473483e-01,  3.803483118694e-01,  2.697704226632e-01,  6.810611849029e-01],
       [ 6.622827828376e-01,  6.447943415836e-01,  4.387842058829e-01,  1.530575702376e+00],
       [ 3.672130860703e-01,  8.309522079704e-01,  9.975487474007e-01,  5.678296337101e-01],
       [ 4.036490000599e-01,  6.865978225967e-06,  8.788095913773e-01, -7.150472427928e-02]])

A2 = np.array([[0.988746460106, 0.351486109477, 0.024911477532, 0.384039749683],
       [0.282104657306, 0.239884151775, 0.36170151991 , 0.903082266861],
       [0.59333290915 , 0.637178863968, 0.241229214635, 0.685595037901],
       [0.013591747828, 0.917926970364, 0.458689093885, 0.157821121254]])

A3 = np.array([[0.131923621844, 0.245316154195, 0.732362341613, 0.957047891764],
       [0.91290446184 , 0.512312007959, 0.391938831444, 0.092509684772],
       [0.648708523652, 0.608576675797, 0.576773587276, 0.065385122929],
       [0.502955480393, 0.084082960221, 0.659487390444, 0.662958739412]])

In [24]:
print("Condition number for A1", la.norm(A1,2)*la.norm(la.inv(A1),2))
print("Condition number for A2", la.norm(A2,2)*la.norm(la.inv(A2),2))
print("Condition number for A3", la.norm(A3,2)*la.norm(la.inv(A3),2))

Condition number for A1 13334923332.407896
Condition number for A2 21.55246648838186
Condition number for A3 15.122449699410625


- From this, we can conclude that A1 is ill-conditioned as it's condition number is very large. If we attempt to invert this matrix, this may result in numbers rounding to 0 which would result in errors in our code. The condition number for A2 and A3 is relatively low, so they are not ill-conditioned.

# Q3b

With $b = [1,2,3,4]$ and $\delta b = [0.1,0,0,0]$ for $A1$ and $A2$ calculate the percentage change in $x$ due to a small change in $b$, i.e., calculate 

$$100\times\frac{\lVert \delta x_i\rVert_2}{\lVert x_i \rVert_2}\quad\text{and}\quad 100\times\frac{\lVert \delta b\rVert_2}{\lVert b \rVert_2}$$

where $(x_i+\delta x_i)  = A_i^{-1}(b+\delta b)$ and $i\in\{1,2\}$.

In [25]:
def GaussianElimination(A, b): 
    n = A.shape[1]
    
    # Append the vector b as a column to the matrix A
    A1 = np.c_[A,b]
    
    i = 0
    while i < n - 1:
        j = i+1
        while j < n:
            A1[j, i+1:] = A1[j, i+1:] - A1[i, i+1:]*A1[j,i]/A1[i,i]
            j += 1
        i += 1
        
    x = np.zeros(n)
    
    i = n-1
    while i >= 0:
        j = i
        x[i] = A1[i,n]
        while j < n-1:
            x[i] -= A1[i,j+1]*x[j+1]
            j += 1
        x[i] = x[i]/A1[i,i]
        i -= 1
    
    return x

b=np.array([1,2,3,4])
deltab=np.array([0.1,0,0,0])
print("Percentage change in b",la.norm(deltab,2)/la.norm(b,2)*100)

x=GaussianElimination(A1, b)
x1=GaussianElimination(A1, b+deltab)
print("Percentage change in x for A1",la.norm(x1-x,2)/la.norm(x,2)*100)

x=GaussianElimination(A2, b)
x1=GaussianElimination(A2, b+deltab)
print("Percentage change in x for A2",la.norm(x1-x,2)/la.norm(x,2)*100)

x=GaussianElimination(A3, b)
x1=GaussianElimination(A3, b+deltab)
print("Percentage change in x for A3",la.norm(x1-x,2)/la.norm(x,2)*100)

Percentage change in b 1.8257418583505536
Percentage change in x for A1 512.6206098890684
Percentage change in x for A2 10.483582220338967
Percentage change in x for A3 2.173811243421905


Which system of equations is more sensitive to small changes in $b$? How could you have guessed this from the answer to the Q3a?

- System A1 is most sensitive to small changes in b. This could have been predicted from part a.) as it has the largest condition number and is hence ill-conditioned.

Commit your notebook to git and push it to GitHub.

# Question 4: eigensystems

In this question we look at finding eigenvalues and eigenvectors

## Q4a

You may use any of NumPy's functions for this sub-question.

Find the eigenvalues and eigenvectors for the below matrix. Print out the eigenvalues sorted by descending value and explicitly show that eigenvalues/eigenvector pairs satisfy $Ax = \lambda x$.

In [26]:
A = np.array([[1,4,5],[4,5,4],[6,7,9]])

In [48]:
eigenSystem = la.eig(A)

lambdax=eigenSystem[0]
x=eigenSystem[1]
sortedlambda=-np.sort(-lambdax)

print("Eigenvalues =", sortedlambda)
print("Eigenvectors =\n", x)

print("Ax - Lambdax")
for i in range(0,3):
    print(np.dot(A,x[:,i])-np.dot(lambdax[i],x[:,i]))
    
print("Rounded Ax - Lambdax")
for i in range(0,3):
    print(np.round(np.abs(np.matrix(np.dot(A,x[:,i])-np.dot(lambdax[i],x[:,i])))))

Eigenvalues = [15.78569318  1.26595327 -2.05164645]
Eigenvectors =
 [[-0.39252008 -0.89589878  0.09818766]
 [-0.44424151  0.36255198 -0.77454142]
 [-0.80534308  0.25675168  0.6248558 ]]
Ax - Lambdax
[-3.55271368e-15 -3.55271368e-15  1.77635684e-15]
[ 4.44089210e-16  1.44328993e-15 -1.11022302e-16]
[-1.55431223e-15 -1.11022302e-15 -1.66533454e-15]
Rounded Ax - Lambdax
[[0. 0. 0.]]
[[0. 0. 0.]]
[[0. 0. 0.]]


# Q4b

Without using NumPy's `la.eig()` (or similar functions), find the 4 eigenvalues and eigenvectors of the following matrix. Hint: Use the power method for the max eigenvalue (given below in `MaxEigenvalue`), the power method applied to the inverse for the smallest eigenvalue, and apply Hotelling's deflation twice to find the second and third eigenvalues/eigenvectors.

In [49]:
A = np.array([[2.65287619, 1.58615494, 1.47170961, 1.40586081],
       [1.58615494, 1.17577323, 0.72084593, 0.79382861],
       [1.47170961, 0.72084593, 1.18111969, 0.6654689 ],
       [1.40586081, 0.79382861, 0.6654689 , 0.84502394]])

In [50]:
def MaxEigenvalue(A, err):
    (m,n) = A.shape
    if(m != n):
        print("Matrix must be square")
        return
    
    # Create a random initial vector
    x = np.random.rand(m)
    
    lam = 0.1
    lamprev = 1
    while np.abs(1-lam/lamprev) > err:
        Ax      = A@x
        lamprev = lam
        lam = la.norm(Ax,2)/la.norm(x,2)
        x = Ax
        
    x = x/la.norm(x)
    return (lam,x)

In [51]:
largestEigen = MaxEigenvalue(A, 1e-14)[0]
lmin = 1/(MaxEigenvalue(la.inv(A), 1e-14)[0])

e1 = MaxEigenvalue(A, 1e-14)[1]
B = A - largestEigen*np.outer(e1, e1)
lsecond = MaxEigenvalue(B, 1e-12)

e2 = MaxEigenvalue(B, 1e-14)[1]
C = B - MaxEigenvalue(B, 1e-14)[0]*np.outer(e2, e2)
lthird = MaxEigenvalue(C, 1e-12)

print("Eigenvalues in decending order:",largestEigen,lsecond[0],lthird[0],lmin)

Eigenvalues in decending order: 5.172971199844757 0.4816692703106071 0.1986227826809928 0.0015297971635957433


Check your answers against Numpy's results from `la.eig(A)`

In [77]:
print("Eigenvalues from la.eig(A):", ", ".join(list(str(la.eig(A)[0][i]) for i in range(0,len(la.eig(A)[0])))))

Eigenvalues from la.eig(A): 5.17297119984476, 0.001529797163595248, 0.19862278268099265, 0.48166927031065465


Commit your notebook to git and push it to GitHub. Upload your completed assignment to BrightSpace.