#  Assignment 5

This assignment covers material on matrices, norms, condition numbers and eigensystems.

The breakdown of the marks is as follows:

Question 0 - [1 mark]  
Question 1 - [7 marks]  
Questino 2 - [6 marks]  
Question 3 - [7 marks]  
Question 4 - [9 marks]  

# Question 0

You should have saved this notebook to your ACM20030-Assignments folder. Now:
- commit the notebook to your local repository
- push the changes to the GitHub

In [1]:
import numpy as np
from numpy import linalg as la
np.set_printoptions(linewidth=200)  # This stops line wrapping of larger matrices

# Question 1 - practice manipulating arrays

This questions asks you write a few functions for manipulating arrays of data

## Q1 a

Write a function that checks if a given $n\times n$ matrix is symmetric. Use only loops and `.shape` function from numpy (do not use any other special numpy functions).

In [179]:
def SymmetryCheck(A):
    (m, n) = A.shape
    if (m!=n):
        print("Matrix is not square")
        return
    i=0
    while i<(m-1):
        x, y=A[i:,i], A[i,i:]
        for j in range(1, len(x)):
            if x[j]!=y[j]:
                print("Matrix is not symmetric")
                return
               
        i+=1
    print("Matrix is symmetric")
    return

Test your function on the two matrices below

In [178]:
A = np.random.rand(5,5)
SymMatrix = (A + A.T)/2

In [180]:
#A
SymmetryCheck(A)
#SymMatrix
SymmetryCheck(SymMatrix)

Matrix is not symmetric
Matrix is symmetric


## Q1 b

Write a function to transpose a general $n\times n$ matrix. Do this by writing loops and not using any special functions like `np.transpose()`, `A.T`, or any functions from any other library (`np.zeroes`, `np.ones`, `np.shape`, etc are all ok to use).

In [181]:
def MatrixTranspose(A):
    (m, n) = A.shape
    if (m!=n):
        print("Matrix is not square")
        return
    i=0
    while i<(m-1):
        x, y=A[i:,i], A[i,i:]
        for j in range(1, len(x)):
            temp=y[j]
            y[j]=x[j]
            x[j]=temp
               
        i+=1
    return A

Check your code by transposing a matrix by checking that $A^T \neq A$ and $(A^T)^T - A = 0$

In [182]:
A = np.random.rand(6,6);
print("Matrix A\n",A)
print("Transpose of A\n", MatrixTranspose(A))
print("A transpose transpose - A\n", MatrixTranspose(MatrixTranspose(A))-A )

Matrix A
 [[9.82096606e-01 8.80075774e-01 2.29497018e-01 3.24814683e-01 4.52211234e-01 7.90409455e-01]
 [6.70526562e-01 7.64196764e-05 3.22292559e-01 9.11589413e-01 4.57393154e-01 9.57532184e-02]
 [3.45393510e-01 4.37679682e-01 5.10073654e-01 6.82617635e-02 2.15686427e-02 4.72108120e-01]
 [2.67619092e-01 5.13848484e-01 9.22928538e-01 5.82921319e-01 2.20506438e-01 2.87286240e-01]
 [2.01643022e-01 4.73187216e-01 2.76892666e-01 1.86582009e-01 8.47407190e-01 5.44007132e-02]
 [7.89358464e-01 1.41080353e-01 5.78215958e-01 9.29332745e-01 9.88725851e-02 9.86874073e-01]]
Transpose of A
 [[9.82096606e-01 6.70526562e-01 3.45393510e-01 2.67619092e-01 2.01643022e-01 7.89358464e-01]
 [8.80075774e-01 7.64196764e-05 4.37679682e-01 5.13848484e-01 4.73187216e-01 1.41080353e-01]
 [2.29497018e-01 3.22292559e-01 5.10073654e-01 9.22928538e-01 2.76892666e-01 5.78215958e-01]
 [3.24814683e-01 9.11589413e-01 6.82617635e-02 5.82921319e-01 1.86582009e-01 9.29332745e-01]
 [4.52211234e-01 4.57393154e-01 2.15686427e

## Q1c

Write a function that finds the maximum entry in a matrix (where the matrix does not need to be square). Do this by writing loops and not using any special functions like `np.max` or any functions from any other library.

In [183]:
def MatrixMax(A):
    i=0
    m=A[0,0]
    while i<A.shape[0]:
        x=A[i,:]
        for j in range(0, len(x)):
            if x[j]>m:
                m=x[j]
        i+=1
    return m

Check your result by comparing to `np.max(A)` for the below random matrix

In [185]:
A = np.random.rand(4,5)

print(A,"\nMaximum entry in A:",MatrixMax(A))

[[0.82170843 0.18300437 0.41093638 0.30631533 0.76366281]
 [0.66268586 0.99866055 0.71659201 0.1768582  0.84750006]
 [0.19226048 0.8271947  0.36282447 0.53632055 0.15385537]
 [0.31935135 0.27483946 0.83839599 0.86564441 0.20163126]] 
Maximum entry in A: 0.9986605475910155


Commit your notebook to git and push it to GitHub.

# Question 2:  matrix norms

In the lectures we focused on the $L^2$-norm. We also briefly mentioned the $L^1$ and $L^\infty$ norm. Let's look at calculating those as well for a general $m\times n$ matrix.

# Q2a

The $L^1$ norm is given by

$$ \lVert A \rVert_1 = \max_j \sum^m_{i=1} |a_{ij}| $$

i.e., it is the max of the sums of the absolute values of each column. Write a function that computes the $L^1$-norm using only loops. The function should use no special numpy functions except `np.abs()` (`np.shape`, `np.inf`, etc are ok to use).

In [194]:
def L1Norm(A):
    i=0
    n=0
    while i<A.shape[1]:
        m=0
        x=A[:,i]
        for j in range(0, len(x)):
            m+=x[j]
        if np.abs(m)>n:
            n=np.abs(m)
        i+=1
    return n

Check your result against NumPy's `la.norm(A,1)` function for the following random matrix

In [198]:
A = np.random.rand(3,4)
print(A)
print("Using L1Norm function, L1 norm =",L1Norm(A))
print("Using la.norm(A,1), L1 norm =",la.norm(A,1))


[[0.81419168 0.40023831 0.88128949 0.50037323]
 [0.29290425 0.00320649 0.15204955 0.48654342]
 [0.29519272 0.27556904 0.71284731 0.93374031]]
Using L1Norm function, L1 norm = 1.9206569547503851
Using la.norm(A,1), L1 norm = 1.9206569547503851


## Q2b

The $L^\infty$ norm is given by 

$$\lVert A \rVert_\infty = \max_i \sum_{j=1}^n |a_{ij}|$$

i.e., it is the max of the sums of the absolute values of each row. Write a function that computes the $L^\infty$-norm using only loops and no special numpy functions.

In [209]:
def LinfNorm(A):
    i=0
    n=0
    while i<A.shape[0]:
        m=0
        x=A[i,:]
        for j in range(0, len(x)):
            m+=x[j]
        if np.abs(m)>n:
            n=np.abs(m)
        i+=1
    return n

Check your result against NumPy's `la.norm(A,np.inf)` function for the following random matrix

In [210]:
A = np.random.rand(3,4)
print(A)
print("Using LinfNorm function, L infinity norm =",LinfNorm(A))
print("Using la.norm(A,1), L infinity norm =",la.norm(A,np.inf))

[[0.39406813 0.90042116 0.5476962  0.60864468]
 [0.73041947 0.80615239 0.53254636 0.26920755]
 [0.93999338 0.63749574 0.71560991 0.65788501]]
Using LinfNorm function, L infinity norm = 2.9509840460480667
Using la.norm(A,1), L infinity norm = 2.9509840460480667


Commit your notebook to git and push it to GitHub.

# Question 3: ill-conditions systems of equations

In this question you can use any of NumPy's functions.

## Q3a

Which of the following three matrices, $A1, A2, A3$, are ill-conditioned. State the reason for your conclusion.

In [7]:
A1 = np.array([[ 2.852416473483e-01,  3.803483118694e-01,  2.697704226632e-01,  6.810611849029e-01],
       [ 6.622827828376e-01,  6.447943415836e-01,  4.387842058829e-01,  1.530575702376e+00],
       [ 3.672130860703e-01,  8.309522079704e-01,  9.975487474007e-01,  5.678296337101e-01],
       [ 4.036490000599e-01,  6.865978225967e-06,  8.788095913773e-01, -7.150472427928e-02]])

A2 = np.array([[0.988746460106, 0.351486109477, 0.024911477532, 0.384039749683],
       [0.282104657306, 0.239884151775, 0.36170151991 , 0.903082266861],
       [0.59333290915 , 0.637178863968, 0.241229214635, 0.685595037901],
       [0.013591747828, 0.917926970364, 0.458689093885, 0.157821121254]])

A3 = np.array([[0.131923621844, 0.245316154195, 0.732362341613, 0.957047891764],
       [0.91290446184 , 0.512312007959, 0.391938831444, 0.092509684772],
       [0.648708523652, 0.608576675797, 0.576773587276, 0.065385122929],
       [0.502955480393, 0.084082960221, 0.659487390444, 0.662958739412]])

# Q3b

With $b = [1,2,3,4]$ and $\delta b = [0.1,0,0,0]$ for $A1$ and $A2$ calculate the percentage change in $x$ due to a small change in $b$, i.e., calculate 

$$100\times\frac{\lVert \delta x_i\rVert_2}{\lVert x_i \rVert_2}\quad\text{and}\quad 100\times\frac{\lVert \delta b\rVert_2}{\lVert b \rVert_2}$$

where $(x_i+\delta x_i)  = A_i^{-1}(b+\delta b)$ and $i\in\{1,2\}$.

Which system of equations is more sensitive to small changes in $b$? How could you have guessed this from the answer to the Q3a?

In [8]:
# Answer here


Commit your notebook to git and push it to GitHub.

# Question 4: eigensystems

In this question we look at finding eigenvalues and eigenvectors

## Q4a

You may use any of NumPy's functions for this sub-question.

Find the eigenvalues and eigenvectors for the below matrix. Print out the eigenvalues sorted by descending value and explicitly show that eigenvalues/eigenvector pairs satisfy $Ax = \lambda x$.

In [50]:
A = np.array([[1,4,5],[4,5,4],[6,7,9]])

# Q4b

Without using NumPy's `la.eig()` (or similar functions), find the 4 eigenvalues and eigenvectors of the following matrix. Hint: Use the power method for the max eigenvalue (given below in `MaxEigenvalue`), the power method applied to the inverse for the smallest eigenvalue, and apply Hotelling's deflation twice to find the second and third eigenvalues/eigenvectors.

In [20]:
A = np.array([[2.65287619, 1.58615494, 1.47170961, 1.40586081],
       [1.58615494, 1.17577323, 0.72084593, 0.79382861],
       [1.47170961, 0.72084593, 1.18111969, 0.6654689 ],
       [1.40586081, 0.79382861, 0.6654689 , 0.84502394]])

Check your answers against Numpy's results from `la.eig(A)`

Commit your notebook to git and push it to GitHub. Upload your completed assignment to BrightSpace.